### ISSUE TITLE
Add An Ushahidi Instance Url

### ISSUE THREAD

**Issue by unstephenk** [ushahidi/platform-android#13]
On initial screen user should be able to add the url to an Ushahidi Instance but not be forced to do so. The user should still be able to explore the application and log in.

**Comment by eyedol** [comment]
Because the app can't really function that much well without setting up a deployment URL, it's best to take the user to a setup screen. Right now, we don't have a demo deployment to point people to so it makes sense to ask them to set one up on initial start. Again, we will review the on boarding process for this. Thanks for pointing it out.
